import { zhCN } from "./zh-CN";

export const enUS = {
  ...zhCN,
  common: { ...zhCN.common, none: "None", hidden: "Hidden", move: "Move {count}", afterMove: "After move {count}", loading: "Connecting to the server…", failed: "Action failed.", backHome: "← Back to Moon Hall", switchToEnglish: "Switch to English", switchToChinese: "Switch to Chinese" },
  nav: { navigation: "Page navigation", guide: "Open game guide", github: "View GitHub repository", bilibili: "Visit Bilibili profile", light: "Switch to light theme", dark: "Switch to dark theme" },
  meta: { moonHall: "Moon Chess | Moon Hall", teaParty: "Silver Moon Tea Party | Moon Chess", lunarOrbit: "Lunar Orbit | Moon Chess" },
  home: { ...zhCN.home, title: "Play beneath the moon; let every move shine.", subtitle: "The moon before us mirrors the moon above.", modes: "Choose a game mode", teaAria: "Enter Silver Moon Tea Party versus AI", orbitAria: "Enter Lunar Orbit", ai: "Play vs AI", free: "Free analysis", teaTitle: "Silver Moon Tea Party", orbitTitle: "Lunar Orbit", teaText: "Play Columbina across the moonlight. Choose your side and difficulty, then make three in a row.", orbitText: "Place freely and inspect removals, winning moves, and real threats.", levels: "Three difficulties", autoReply: "Auto reply", history: "Full history", backend: "Server adjudication", threats: "Threat analysis", undo: "Step back", enterTea: "Take your seat", enterOrbit: "Trace the orbit", teaFeatures: "Silver Moon Tea Party features", orbitFeatures: "Lunar Orbit features" },
  teaParty: { ...zhCN.teaParty, title: "Moon Chess · Silver Moon Tea Party", subtitle: "Play beneath the silver moon: know which piece will fade before you seek victory.", restart: "Begin anew", restartTitle: "Clear the board and begin a new Silver Moon Tea Party.", undo: "Reverse orbit", undoTitle: "Retrace the moonlight and undo the previous round.", actions: "Game actions", thinking: "Columbina is thinking…", startFailed: "Could not start a new game.", undoFailed: "Could not undo the move.", moveFailed: "Could not place the piece.", aiFailed: "Columbina could not move." },
  lunarOrbit: { ...zhCN.lunarOrbit, title: "Moon Chess · Lunar Orbit", subtitle: "Three is appearance; four is essence; seven is their path beyond.", restart: "Restart analysis", restartTitle: "Clear the board and restart Lunar Orbit.", undo: "Undo step", undoTitle: "Undo the previous analysis step.", actions: "Analysis actions", actionFailed: "Action failed.", settings: "Analysis settings", details: "Analysis details" },
  game: { ...zhCN.game, board: "Moon Chess board", current: "Current: {player}", ended: "Game over", yourTurn: "{player}'s turn", preview: "Removal preview:", position: "Position {position}", cellWithPiece: "Position {position}, {piece}", legal: "Legal", winning: "Win", threat: "Threat", status: "Current status", currentPlayer: "Current player", actionStatus: "Action status", pending: "Remove first", upcoming: "Next preview", legalMoves: "Legal moves", result: "Game result", winner: "{player} wins", draw: "Draw", playing: "In play", winningLine: "Winning line: {moves}", drawAfter: "Draw after move {count}.", retained: "Retained after removal", directWins: "Current winning moves", realThreats: "Opponent real threats", noOwnRemoval: "No piece will be removed before this move.", pendingRemoval: "{piece} will be removed first.", nextRemoval: "{piece} will be removed before the next turn.", noNextRemoval: "No old piece is due for removal after this move.", hasDirectWins: "{player}'s winning moves: {moves}.", noDirectWins: "{player} has no immediate winning move.", hasThreats: "{player}'s real threats next turn: {moves}.", noThreats: "{player} has no real threat next turn.", wonAnalysis: "Game over: {player} wins.", drawAnalysis: "Game over: draw.", moveEvent: "Move {count}: {piece} placed at {position}.", moveEventBefore: "Move {count}: {removed} was removed first; {piece} placed at {position}.", moveEventAfter: "Move {count}: {piece} placed at {position}; then {removed} was removed.", moveEventWinner: "{event} {player} wins." },
  settings: { ...zhCN.settings, configuration: "Game settings", side: "Player side", first: "Traveler goes first", second: "Traveler goes second", opponentDifficulty: "Opponent difficulty", display: "Display", numbers: "Show cell numbers", legal: "Show legal moves", wins: "Show winning moves", threats: "Show real threats", preview: "Show removal preview" },
  difficulty: { easy: "Rainbow Moon · Easy", medium: "Eternal Moon · Medium", hard: "Frost Moon · Hard" },
  history: { title: "Move history", count: "{count} moves", empty: "No moves yet." }, analysis: { title: "Analysis details", backend: "Server adjudication", empty: "No analysis available." },
  ai: { ...zhCN.ai, panel: "AI controls", title: "Rules AI", difficulty: "Difficulty", hint: "Show hint", move: "AI move", autoReply: "AI auto-reply", explanation: "AI explanation", actual: "Played move", recommended: "Recommended move", outcome: "Expected outcome", confidence: "Method", candidates: "Candidate evaluation", point: "Move", result: "Result", score: "Score", distance: "Distance", reason: "Reason", empty: "No AI explanation yet.", win: "Win", loss: "Loss", unknown: "Unknown", random: "Random", heuristic: "Heuristic", search: "Search", easyProfile: "Easy AI can make random mistakes.", selectedWinning: "Winning moves: {moves}; selected {move}.", blockedThreat: "{player}'s real threats: {moves}; blocked with {move}.", randomSelected: "Randomly selected {move}.", missedWinning: "Did not select winning moves {moves}.", missedThreat: "Did not block threats {moves}.", highestScore: "Highest heuristic score: {move}.", searchSelected: "Search: {move} yields {outcome} in {plies} plies.", otherLose: "Some other moves lose within {plies} plies.", drawing: "Other drawing moves: {moves}.", optimal: "Hard AI selected theoretical best move {move}.", positionBonus: "+{points} {kind}", center: "center", corner: "corner", edge: "edge", createsThreat: "+{points} creates a real threat", alignsPair: "+{points} aligns own pair", blocksPair: "+{points} blocks opponent pair", occupiesWin: "+{points} occupies opponent win", legalMove: "Basic legal move", winningMove: "Winning move", blocksThreat: "Blocks real threat", randomCandidate: "Legal random candidate", searchResult: "Search result: {outcome}, {plies} plies away." },
  guide: { ...zhCN.guide, kicker: "Game guide", title: "Moon Chess Guide", close: "Close", closeAria: "Close game guide", content: "Guide contents", quick: "Quick start", rules: "Full rules", modes: "Modes", markers: "Board markers", oneLine: "The rule in one sentence", oneLineText: "Take turns on a 3×3 board and make three in a row—but once a player gets a fourth piece, their oldest piece disappears first.", step1: "Choose a highlighted legal cell.", step2: "Watch the pink removal preview: the active player's oldest piece may leave first.", step3: "Green marks immediate wins; orange marks the opponent's real threat next turn.", step4: "Any horizontal, vertical, or diagonal line of three wins immediately.", board: "Board", boardText: "The board has cells 1 through 9: three rows, three columns, and two diagonals can win.", move: "Move", moveText: "Players take turns placing on legal cells. An occupied cell is only legal when that piece disappears first this turn.", removal: "Removal", removalText: "Each player stably keeps at most three pieces. If the active player already has three, their oldest piece disappears before the new one is placed.", result: "Result", resultText: "Check for three in a row immediately after placement. If nobody wins after move 14, the game is a draw.", teaText: "The home-page AI mode. Choose whether Traveler goes first, set Columbina's difficulty, and start a game.", orbitText: "A manual analysis sandbox for undoing, testing lines, and observing removals, wins, and threats.", number: "Cell number", numberText: "The board's 1–9 labels identify each cell.", legal: "Legal move", legalText: "A cell available on this turn.", win: "Immediate win", winText: "A cell that forms three in a row immediately.", threat: "Real threat", threatText: "A cell where the opponent can still win next turn after removal rules apply.", preview: "Removal preview", previewText: "The oldest piece due to leave this or next turn." },
  footer: { disclaimer: "A fan-made rules demonstration tool, unaffiliated with the official game." }, player: { traveler: "Traveler", columbina: "Columbina" },
  errors: { generic: "Request failed ({status}).", network: "Network request failed.", gameNotFound: "Game not found.", gameFinished: "The game is over.", invalidMove: "Position {position} is not legal now.", noLegalMoves: "No legal moves are available.", gameCapacity: "The server is at game capacity. Please try again later.", rateLimited: "Too many requests. Try again in {retry_after} seconds.", aiBusy: "AI is busy. Please try again later.", validation: "Invalid request parameters." }
} satisfies typeof zhCN;
