export const zhCN = {
  common: { none: "无", hidden: "已隐藏", move: "第 {count} 手", afterMove: "第 {count} 手后", loading: "正在连接后端…", failed: "操作失败。", backHome: "← 返回银月之庭", switchToEnglish: "切换到英语", switchToChinese: "切换到中文" },
  nav: { navigation: "页面导航", guide: "查看规则说明", github: "查看 GitHub 仓库", bilibili: "访问 Bilibili 主页", light: "切换到浅色模式", dark: "切换到深色模式" },
  meta: { moonHall: "月亮棋｜银月之庭", teaParty: "银月茶会｜月亮棋模拟器", lunarOrbit: "月轨推演｜月亮棋模拟器" },
  home: { title: "月下对弈，落子成光", subtitle: "眼前月是天上月，月上人是心上人。", modes: "选择游戏模式", teaAria: "进入银月茶会 AI 对战", orbitAria: "进入月轨推演", ai: "AI 对战", free: "自由推演", teaTitle: "银月茶会", orbitTitle: "月轨推演", teaText: "与哥伦比娅隔月对弈。选择席位与难度，在月影更替间取得三连。", orbitText: "自由落子，观察旧子消失顺序、当前胜点与对手真实威胁。", levels: "三档难度", autoReply: "自动应手", history: "完整棋谱", backend: "后端判定", threats: "威胁分析", undo: "逐步回退", enterTea: "入席对弈", enterOrbit: "推演月轨", teaFeatures: "银月茶会特性", orbitFeatures: "月轨推演特性" },
  teaParty: { title: "月亮棋·银月茶会", subtitle: "与银月对弈；若想取胜，须先看清哪颗月亮将要落下。", restart: "再启银月", restartTitle: "清空当前棋局，重新开始一场银月茶会。", undo: "逆转月轨", undoTitle: "沿月影回溯，撤回上一轮对弈。", actions: "棋局操作", thinking: "哥伦比娅思考中…", startFailed: "新开棋局失败。", undoFailed: "悔棋失败。", moveFailed: "落子失败。", aiFailed: "哥伦比娅落子失败。" },
  lunarOrbit: { title: "月亮棋·月轨推演", subtitle: "三是表象，四是本征；七，是二者交叠后的垂直超越之径。", restart: "重新推演", restartTitle: "清空当前棋局，重新开始一次月轨推演。", undo: "回退一步", undoTitle: "撤回上一步推演。", actions: "推演操作", actionFailed: "操作失败。", settings: "推演配置", details: "推演详情" },
  game: { board: "月亮棋棋盘", current: "当前：{player}", ended: "对局结束", yourTurn: "轮到 {player}", preview: "消失预告：", position: "位置 {position}", cellWithPiece: "位置 {position}，{piece}", legal: "可下", winning: "胜点", threat: "威胁", status: "当前状态", currentPlayer: "当前行动方", actionStatus: "行动状态", pending: "本手先消", upcoming: "下回预告", legalMoves: "合法落点", result: "对局结果", winner: "{player} 胜利", draw: "平局", playing: "对弈中", winningLine: "胜线：{moves}", drawAfter: "第 {count} 手后，判定为平局。", retained: "消子后保留", directWins: "当前方直接胜点", realThreats: "对手真实威胁", noOwnRemoval: "本手没有自己的棋子先消失。", pendingRemoval: "{piece} 会先消失。", nextRemoval: "下一回合前 {piece} 会消失。", noNextRemoval: "本手结束后暂时没有旧子消失预告。", hasDirectWins: "{player} 当前直接胜点是 {moves}。", noDirectWins: "{player} 当前没有直接胜点。", hasThreats: "{player} 下一回合的真实威胁是 {moves}。", noThreats: "{player} 下一回合没有真实威胁。", wonAnalysis: "棋局已结束，{player} 获胜。", drawAnalysis: "棋局已结束，判定为平局。", moveEvent: "第 {count} 手：{piece} 落在 {position}。", moveEventBefore: "第 {count} 手：{removed} 先消失，{piece} 落在 {position}。", moveEventAfter: "第 {count} 手：{piece} 落在 {position}，随后 {removed} 消失。", moveEventWinner: "{event} {player} 胜利。" },
  settings: { configuration: "对弈配置", side: "执棋顺序", first: "旅行者先手", second: "旅行者后手", opponentDifficulty: "对手难度", display: "界面显示", numbers: "显示格号", legal: "显示合法落点", wins: "直接胜点", threats: "真实威胁", preview: "消失预告" },
  difficulty: { easy: "虹月 · 简单", medium: "恒月 · 中等", hard: "霜月 · 困难" },
  history: { title: "棋谱历史", count: "{count} 手", empty: "尚未落子。" },
  analysis: { title: "推演详情", backend: "后端判定", empty: "暂无推演说明。" },
  ai: { panel: "AI 控制区", title: "规则 AI", difficulty: "难度", hint: "查看推荐", move: "AI 落子", autoReply: "AI 自动回应", explanation: "AI 说明区", actual: "实际落子", recommended: "推荐落子", outcome: "理论结果", confidence: "判断方式", candidates: "候选落子评估", point: "点位", result: "结果", score: "分数", distance: "距离", reason: "理由", empty: "尚未生成 AI 说明。", win: "胜", loss: "负", unknown: "未知", random: "随机", heuristic: "启发式", search: "搜索", easyProfile: "简单 AI 会随机犯错。", selectedWinning: "存在胜点 {moves}，选择 {move}。", blockedThreat: "{player} 的真实威胁为 {moves}，选择 {move} 防守。", randomSelected: "随机选择 {move}。", missedWinning: "未选择胜点 {moves}。", missedThreat: "未防守真实威胁 {moves}。", highestScore: "启发式评分最高的是 {move}。", searchSelected: "搜索显示落在 {move} 可得到 {outcome}，距离 {plies} 手。", otherLose: "其他部分落子会在 {plies} 手内导致失败。", drawing: "另有和棋候选：{moves}。", optimal: "困难 AI 选择理论最优落子 {move}。", positionBonus: "+{points} {kind}", center: "中心", corner: "角", edge: "边", createsThreat: "+{points} 制造真实威胁", alignsPair: "+{points} 自己两子共线", blocksPair: "+{points} 阻断对方共线", occupiesWin: "+{points} 占住对手需要点", legalMove: "基础合法落子", winningMove: "直接胜点", blocksThreat: "可堵对手威胁", randomCandidate: "合法随机候选", searchResult: "搜索结果：{outcome}，距离 {plies} 手。" },
  guide: { kicker: "规则说明", title: "月亮棋指南", close: "关闭", closeAria: "关闭规则说明", content: "指南内容", quick: "快速上手", rules: "完整规则", modes: "模式说明", markers: "界面标记", oneLine: "一句话规则", oneLineText: "在九宫格里轮流落子，三子连线获胜；但从第 4 枚同方棋子开始，最早落下的旧子会先消失。", step1: "看高亮的合法落点，选择一个空格落子。", step2: "留意粉色消失预告：轮到一方时，自己的最旧棋子可能会先离场。", step3: "绿色是当前方直接胜点，橙色是对手下一回合的真实威胁。", step4: "落子后如果形成横、竖、斜任意三连，立即获胜。", board: "棋盘", boardText: "棋盘是 1 到 9 的九宫格，胜线包括 3 横、3 竖、2 条斜线。", move: "落子", moveText: "双方轮流在合法位置落一枚棋子。被占用的位置不可落子，除非占用它的棋子会在本回合先消失。", removal: "消子", removalText: "每方场上最多稳定保留 3 枚棋子。轮到某方行动且该方已有 3 枚棋子时，最早落下的一枚先消失，然后再落新子。", result: "胜负", resultText: "落子后先判断三连胜利。若第 14 手结束后仍未分胜负，棋局判为平局。", teaText: "首页对弈模式。你可以选择旅行者先手或后手，设置哥伦比娅的 AI 难度，然后直接开始一局。", orbitText: "分析沙盒模式。双方都由你手动落子，适合回退、试招、观察消子后的胜点和威胁。", number: "格号", numberText: "棋盘上的 1-9 编号，方便描述落点。", legal: "合法落点", legalText: "当前回合可以落子的格子。", win: "直接胜点", winText: "当前方落下即可形成三连的位置。", threat: "真实威胁", threatText: "对手下一回合在消子规则生效后仍然能取胜的位置。", preview: "消失预告", previewText: "本回合或下一回合会先离场的最旧棋子。" },
  footer: { disclaimer: "玩家自制规则演示工具，与游戏官方无关联。" },
  player: { traveler: "旅行者", columbina: "哥伦比娅" },
  errors: { generic: "请求失败（{status}）。", network: "网络请求失败。", gameNotFound: "棋局不存在。", gameFinished: "棋局已结束。", invalidMove: "位置 {position} 当前不可落子。", noLegalMoves: "当前没有合法落子。", gameCapacity: "服务器当前棋局过多，请稍后重试。", rateLimited: "请求过于频繁，请在 {retry_after} 秒后重试。", aiBusy: "AI 当前繁忙，请稍后重试。", validation: "请求参数无效。" }
};
